import { Dashboard, Employees, Events, Dogs, Volunteers, Login, Register, Workflows, UserSettings, ForgotPassword } from "pages";

var routes = [
  {
    path: "/dashboard",
    layout: "/admin",
    name: "Dashboard",
    icon: "home",
    show: true,
    component: Dashboard,
  },
  {
    path: "/dogs",
    layout: "/admin",
    name: "Dogs",
    icon: "dog",
    show: true,
    component: Dogs,
  },
  {
    path: "/employees",
    layout: "/admin",
    name: "Employees",
    icon: "user-clock",
    show: true,
    component: Employees,
  },
  {
    path: "/volunteers",
    layout: "/admin",
    name: "Volunteers",
    icon: "hands-helping",
    show: true,
    component: Volunteers,
  },
  {
    path: "/events",
    layout: "/admin",
    name: "Events",
    icon: "calendar-plus",
    show: true,
    component: Events,
  },
  {
    path: "/workflows",
    layout: "/admin",
    name: "Workflows",
    icon: "bezier-curve",
    show: true,
    component: Workflows,
  },
  {
    path: "/user-settings",
    layout: "/admin",
    name: "User Settings",
    icon: "bezier-curve",
    show: false,
    component: UserSettings,
  },
  {
    path: "/login",
    layout: "/auth",
    name: "Login",
    icon: "home",
    show: true,
    component: Login,
  },
  {
    path: "/register",
    layout: "/auth",
    name: "Register",
    icon: "home",
    show: true,
    component: Register,
  },
  {
    path: "/forgot-password",
    layout: "/auth",
    name: "Forgot Password",
    icon: "home",
    show: true,
    component: ForgotPassword,
  },
];

export default routes;
